e_olstest<-function(explaining=0){
if(explaining==0) {
cat("# install.packages('lmtest') ", '\n')
cat("# install.packages('prais') ", '\n')
cat(" ", '\n')
cat("library(dplyr); library(car); library(prais); library(lmtest); library(aj412); library(readxl) ", '\n')
cat(" ", '\n')
cat("*** 이분산성 Test *** ", '\n')
cat("  Adata<-read.csv('Data2_Zuehlke.csv', header=TRUE) ", '\n')
cat("  아무거나<-lm(sp~age+lot+beds+gar, data=Adata) ", '\n')
cat("  lmtest::bptest(아무거나) ", '\n')
cat(" ", '\n')
cat("# 횡단면자료(Cross-sectional Data)의 sandwich패키지의 HC3형의 SE표본오차 사용 # ", '\n')
cat("  lmtest::coeftest(아무거나, vcov.=sandwich::vcovHC(아무거나, type='HC3')) ", '\n')
cat(" ", '\n')
cat("*** 시계열자료의 DW Test 및 자료의 차분 *** ", '\n')
cat("  Adata<-read_excel('Data39_Time_Series_data.xlsx')  ", '\n')
cat("  Adata$date0<-ts(Adata, start = c(1951, 1), frequency = 4 )  ", '\n')
cat("  plot(Adata$date0, Adata) ", '\n')
cat("  아무거나1 <- lm( log(gdp) ~ log(invest) +unemp, data=Adata) ", '\n')
cat("  durbinWatsonTest(아무거나1) ", '\n')
cat(" ", '\n')
cat("*** 자료의 차분 ***  ", '\n')
cat("  dlngdp<-diff(log(Adata$gdp)) ", '\n')
cat("  dlninvest<-diff(log(Adata$invest)) ", '\n')
cat("  dunemp<-diff(Adata$unemp) ", '\n')
cat("  아무거나2<-lm(dlngdp~dlninvest+dunemp) ", '\n')
cat("  durbinWatsonTest(아무거나2) ", '\n')
cat(" ", '\n')
cat("*** Prais-winsten으로 시계열자료 분석 *** ", '\n')
cat("  아무거나.pw <- prais_winsten(gdp ~ invest + unemp, data = Adata, index = 'time') ", '\n')
cat("  summary(아무거나.pw) ", '\n')
cat(" ", '\n')
cat("*** Hand-made Newey-West Standard Error *** ", '\n')
cat("  Adata<-read_excel('Data39_Time_Series_data.xlsx')  ", '\n')
cat("  Adata <- cbind(Adata$gdp, 1, Adata$invest, Adata$unemp) %>% as.tbl_df()  ", '\n')
cat("  names(Adata) <- c('gdp', 'ones', 'invest', 'unemp') ", '\n')
cat("  optLag <- (nrow(Adata))^(1/4)  ", '\n')
cat("  olsNW(Adata, 'gdp', c('ones', 'invest', 'unemp'), optLag) ", '\n')
}}

