e_panel<-function(explaining=0){
if(explaining==0) {
cat("   ", '\n')
cat(" ############ Cross-Sectional Data ############  ", '\n')
cat(" *** Cross-Sectional Data: 이분산성 점검 ***  ", '\n')
cat(" library(lmtest)  ; library(plm)   ", '\n')
cat(" Gdata<-Grunfeld  ", '\n')
cat(" Gdata<-pdata.frame(Gdata, index=c('firm', 'year'))    ", '\n')
cat(" 결과 <- lm(inv ~ value + capital, data = Gdata)  ", '\n')
cat(" bptest(결과)    ", '\n')
cat("   ", '\n')
cat(" *** Heteroskedasticity consistent coefficients (Arellano) ***    ", '\n')
cat(" coeftest(결과, vcov. = vcovHC, type = 'HC1')  ", '\n')
cat("   ", '\n')
cat("    - arellano - both heteroskedasticity and serial correlation. Recommended for fixed effects.    ", '\n')
cat("    - vcovHC(): three heteroskedasticity-consistent covariance estimators    ", '\n')
cat("    - white1 - for general heteroskedasticity but no serial correlation. Recommended for random effects.    ", '\n')
cat("    - white2 - is 'white1' restricted to a common variance within groups. Recommended for random effects.    ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat(" ############ Panel Data ############  ", '\n')
cat(" library(plm)   ", '\n')
cat(" # Grunfeld변수: firm  year  inv  value  capital  ", '\n')
cat(" # inv: gross Investment  ", '\n')
cat(" # value: value of the firm  ", '\n')
cat(" # capital: stock of plant and equipment  ", '\n')
cat(" # Gdata<-data('Grunfeld', package = 'plm')  ", '\n')
cat("   ", '\n')
cat(" *** 그래프: 지역별 이분산성  ***  ", '\n')
cat(" library(gplots)  ", '\n')
cat(" plotmeans(Gdata$inv~Gdata$firm)  ", '\n')
cat("   ", '\n')
cat(" *** 그래프: 시간별 이분산성  ***  ", '\n')
cat(" plotmeans(Gdata$inv~Gdata$year)  ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" *** 패널데이터 변수의 단위근 검정 ***   ", '\n')
cat(" # test=c('levinlin', 'ips', 'madwu', 'Pm', 'invnormal)  ", '\n')
cat(" # exo = c('none', 'intercept', 'trend'), ips테스트를 사용할 경우 exo는 intercept 또는 trend를 선택  ", '\n')
cat(" # lags = c('SIC', 'AIC', 'Hall')  ", '\n')
cat(" # pmax는 lag의 최대 갯수인 데, 2~10까지 변화시키면서 검정통계량의 변화를 점검해 결과 판독하자  ", '\n')
cat("   ", '\n')
cat(" library(plm)    ", '\n')
cat(" Gdata<-Grunfeld  ", '\n')
cat(" Gdata<-pdata.frame(Gdata, index=c('firm', 'year'))    ", '\n')
cat(" purtest(inv ~ 1, data = Gdata, index = c('firm', 'year'),  pmax = 4, test = 'madwu')  ", '\n')
cat(" # 결과해석: inv변수가 non-stationary이므로 차분해야 함    ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat(" *** R의 plm패키지에서 각 모형을 나타내는 명령문 ***   ", '\n')
cat("     random.method = 'swar' / 'amemiya' / 'walhus' / 'nerlove'    ", '\n')
cat("     pooled OLS (model = 'pooling') / fixed effects (model = 'within') / random effects (model = 'random')    ", '\n')
cat("     first differences (model = 'fd') / between (model = 'between')    ", '\n')
cat("   ", '\n')
cat(" Gdata<-pdata.frame(Gdata, index=c('firm', 'year'))    ", '\n')
cat(" gp <- plm(inv ~ value + capital, data = Gdata, model = 'pooling')    ", '\n')
cat(" gi <- plm(inv ~ value + capital, data = Gdata, effect = 'individual', model = 'within')    ", '\n')
cat(" gt <- plm(inv ~ value + capital, data = Gdata, effect = 'time', model = 'within')    ", '\n')
cat(" gd <- plm(inv ~ value + capital, data = Gdata, effect = 'twoways', model = 'within')    ", '\n')
cat("   ", '\n')
cat(" *** 대립가설: gp(Pooled)모델이 gi(Fixed모델의 Individual모형)모델보다 우수하다    ", '\n')
cat(" pFtest(gi, gp)    ", '\n')
cat(" *** 대립가설: gp(Pooled)모델이 gt(Fixed모델의 Time모형)모델보다 우수하다    ", '\n')
cat(" pFtest(gt, gp)    ", '\n')
cat(" *** 대립가설: gp(Pooled)모델이 gd모델(Fixed모델의 Individual+Teim모형)보다 우수하다    ", '\n')
cat(" pFtest(gd, gp)    ", '\n')
cat("   ", '\n')
cat(" *** Hausman Tets ***  ", '\n')
cat(" -- 대립가설: Random effect model이 Fixed effect model 보다 우수하다    ", '\n')
cat(" Fixed결과 <- plm(inv ~ value + capital, data = Gdata, effect = 'individual', index=c('firm', 'year'), model='within')    ", '\n')
cat(" Random결과 <- plm(inv ~ value + capital, data = Gdata, index=c('firm', 'year'), model='random')    ", '\n')
cat(" phtest(Fixed결과, Random결과)    ", '\n')
cat("   ", '\n')
invisible(readline(prompt="Press [enter] to continue"))
cat("   ", '\n')
cat(" *** Cross-sectional dependence 점검 ***  ", '\n')
cat(" -- 대립가설: p-value가 0.05보다 작으면 NULL을 기각하고 cross-sectional dependence가 존재    ", '\n')
cat(" 결과 <- plm(inv ~ value + capital, data = Gdata, index=c('firm', 'year') )    ", '\n')
cat(" pcdtest(결과, test=c('lm'))    ", '\n')
cat(" pcdtest(결과, test=c('cd'))    ", '\n')
cat("   ", '\n')
cat(" *** Panel Data: Panel data의 자기상관 및 이분산성의 점검 ***    ", '\n')
cat(" Gdata<-pdata.frame(Gdata, index=c('firm', 'year')) ", '\n')
cat(" 결과 <- plm(inv ~ value + capital, data = Gdata, index=c('firm', 'year'), model='random') ", '\n')
cat(" pdwtest(결과, alternative='two.sided')    ", '\n')
cat(" pbgtest(결과)  # Breusch–Godfrey Test for Panel Models    ", '\n')
cat("   ", '\n')
cat(" *** Heteroskedasticity consistent coefficients (Arellano) ***    ", '\n')
cat(" 결과 <-plm(inv ~ value + capital, data = Gdata, )  ", '\n')
cat(" coeftest(결과, vcovHC(결과, method = 'arellano'))    ", '\n')
cat("   ", '\n')
cat("    - arellano - both heteroskedasticity and serial correlation. ", '\n')
cat("    - vcovHC(): three heteroskedasticity-consistent covariance estimators    ", '\n')
cat("    - white1 - for general heteroskedasticity but no serial correlation. Recommended for random effects.    ", '\n')
cat("    - white2 - is 'white1' restricted to a common variance within groups. Recommended for random effects.    ", '\n')


}}
